# Generated by Django 4.1.11 on 2023-11-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0192_rename_critical_context_debt_context_type_critical_debt_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='debt_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_context'),
        ),
        migrations.AlterField(
            model_name='debt_context',
            name='lifecycle',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('production', 'Production'), ('retirement', 'Retirement')], max_length=12, null=True),
        ),
    ]
