# Generated by Django 4.1.11 on 2023-11-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0193_engagement_debt_context_alter_debt_context_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='debt_context_grade',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='debt_context_grade_a',
            field=models.IntegerField(default=90, help_text="Percentage score for an 'A' >=", verbose_name='Grade A'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='debt_context_grade_b',
            field=models.IntegerField(default=80, help_text="Percentage score for a 'B' >=", verbose_name='Grade B'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='debt_context_grade_c',
            field=models.IntegerField(default=70, help_text="Percentage score for a 'C' >=", verbose_name='Grade C'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='debt_context_grade_d',
            field=models.IntegerField(default=60, help_text="Percentage score for a 'D' >=", verbose_name='Grade D'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='debt_context_grade_f',
            field=models.IntegerField(default=59, help_text="Percentage score for an 'F' <=", verbose_name='Grade F'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='enable_debt_context_grade',
            field=models.BooleanField(default=False, help_text='Displays a grade letter next to a debt_context to show the overall health.', verbose_name='Enable Debt_Context Grading'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='enable_debt_context_tag_inheritance',
            field=models.BooleanField(default=False, help_text='Enables debt_context tag inheritance globally for all debt_contexts. Any tags added on a debt_context will automatically be added to all Engagements, Tests, and Findings', verbose_name='Enable Debt_Context Tag Inheritance'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='debt_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_context'),
        ),
    ]
