# Generated by Django 4.1.11 on 2023-11-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0196_tagulous_debt_test_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_item',
            name='test',
            field=models.ForeignKey(editable=False, help_text='The test that is associated with this flaw.', on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test', verbose_name='Debt_Test'),
        ),
    ]
