# Generated by Django 4.1.11 on 2023-11-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0197_alter_debt_item_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Engagement_Presets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Brief description of preset.', max_length=500)),
                ('notes', models.CharField(blank=True, help_text='Description of what needs to be tested or setting up environment for testing', max_length=2000, null=True)),
                ('scope', models.CharField(blank=True, default=None, help_text="Scope of Debt_Engagement testing, IP's/Resources/URL's)", max_length=800)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('debt_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_context')),
                ('network_locations', models.ManyToManyField(blank=True, default=None, to='dojo.network_locations')),
                ('test_type', models.ManyToManyField(blank=True, default=None, to='dojo.test_type')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
