# Generated by Django 4.1.11 on 2023-11-13 07:52

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0198_debt_engagement_presets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt_item',
            name='endpoints',
        ),
        migrations.CreateModel(
            name='Tagulous_Debt_Endpoint_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tagulous_Debt_Endpoint_inherited_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Debt_Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, help_text="The communication protocol/scheme such as 'http', 'ftp', 'dns', etc.", max_length=20, null=True)),
                ('userinfo', models.CharField(blank=True, help_text="User info as 'alice', 'bob', etc.", max_length=500, null=True)),
                ('host', models.CharField(blank=True, help_text="The host name or IP address. It must not include the port number. For example '127.0.0.1', 'localhost', 'yourdomain.com'.", max_length=500, null=True)),
                ('port', models.IntegerField(blank=True, help_text='The network port associated with the debt_endpoint.', null=True)),
                ('path', models.CharField(blank=True, help_text="The location of the resource, it must not start with a '/'. For example debt_endpoint/420/edit", max_length=500, null=True)),
                ('query', models.CharField(blank=True, help_text="The query string, the question mark should be omitted.For example 'group=4&team=8'", max_length=1000, null=True)),
                ('fragment', models.CharField(blank=True, help_text="The fragment identifier which follows the hash mark. The hash mark should be omitted. For example 'section-13', 'paragraph-2'.", max_length=500, null=True)),
                ('debt_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_context')),
                ('debt_endpoint_params', models.ManyToManyField(blank=True, editable=False, to='dojo.endpoint_params')),
                ('debt_items', models.ManyToManyField(blank=True, through='dojo.Debt_Endpoint_Status', to='dojo.debt_item', verbose_name='Debt_Items')),
                ('inherited_tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Internal use tags sepcifically for maintaining parity with debt_context. This field will be present as a subset in the tags field', to='dojo.tagulous_debt_endpoint_inherited_tags')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Add tags that help describe this debt_endpoint. Choose from the list or add new tags. Press Enter key to add.', to='dojo.tagulous_debt_endpoint_tags')),
            ],
            options={
                'ordering': ['debt_context', 'host', 'protocol', 'port', 'userinfo', 'path', 'query', 'fragment'],
            },
        ),
        migrations.AddField(
            model_name='debt_item',
            name='debt_endpoints',
            field=models.ManyToManyField(blank=True, help_text='The hosts within the debt_context that are susceptible to this flaw. + The status of the debt_endpoint associated with this flaw (Vulnerable, Mitigated, ...).', through='dojo.Debt_Endpoint_Status', to='dojo.debt_endpoint', verbose_name='Debt_Endpoints'),
        ),
        migrations.AlterField(
            model_name='debt_endpoint_status',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_status_debt_endpoint', to='dojo.debt_endpoint'),
        ),
        migrations.AddIndex(
            model_name='debt_endpoint',
            index=models.Index(fields=['debt_context'], name='dojo_debt_e_debt_co_d4794c_idx'),
        ),
    ]
