# Generated by Django 4.1.11 on 2023-11-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0199_remove_debt_item_endpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_endpoint_status',
            name='debt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_debt_item', to='dojo.debt_item'),
        ),
        migrations.AlterField(
            model_name='debt_endpoint_status',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_debt_endpoint', to='dojo.debt_endpoint'),
        ),
    ]
