# Generated by Django 4.1.11 on 2023-11-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0201_debt_jira_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Test_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('static_tool', models.BooleanField(default=False)),
                ('dynamic_tool', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='debt_test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test_type'),
        ),
    ]
