# Generated by Django 4.1.11 on 2023-11-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0202_debt_test_type_alter_debt_test_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_JIRA_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(max_length=200)),
                ('jira_key', models.CharField(max_length=200)),
                ('jira_creation', models.DateTimeField(help_text='The date a Jira issue was created from this debt_item.', null=True, verbose_name='Jira creation')),
                ('jira_change', models.DateTimeField(help_text='The date the linked Jira issue was last modified.', null=True, verbose_name='Jira last update')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_500e1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_fafa37_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_7c44ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_f1be17_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_ddfe9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_90a5d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_c85d21_idx',
        ),
        migrations.RemoveIndex(
            model_name='debt_item',
            name='dojo_debt_i_test_id_7b1ad6_idx',
        ),
        migrations.RemoveField(
            model_name='debt_item',
            name='test',
        ),
        migrations.AddField(
            model_name='debt_item',
            name='debt_test',
            field=models.ForeignKey(default=1, editable=False, help_text='The debt_test that is associated with this flaw.', on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test', verbose_name='Debt_Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt_item',
            name='false_p',
            field=models.BooleanField(default=False, help_text='Denotes if this flaw has been deemed a false positive by the debt_tester.', verbose_name='False Positive'),
        ),
        migrations.AlterField(
            model_name='debt_item',
            name='last_reviewed',
            field=models.DateTimeField(editable=False, help_text="Provides the date the flaw was last 'touched' by a debt_tester.", null=True, verbose_name='Last Reviewed'),
        ),
        migrations.AlterField(
            model_name='debt_item',
            name='last_status_update',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of ladebt_test status update (change in status related fields).', null=True, verbose_name='Last Status Update'),
        ),
        migrations.AlterField(
            model_name='debt_item',
            name='out_of_scope',
            field=models.BooleanField(default=False, help_text='Denotes if this flaw falls outside the scope of the debt_test and/or debt_engagement.', verbose_name='Out Of Scope'),
        ),
        migrations.AlterField(
            model_name='debt_item',
            name='verified',
            field=models.BooleanField(default=False, help_text='Denotes if this flaw has been manually verified by the debt_tester.', verbose_name='Verified'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'active', 'verified'], name='dojo_debt_i_debt_te_9b7d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'is_mitigated'], name='dojo_debt_i_debt_te_1f4ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'duplicate'], name='dojo_debt_i_debt_te_2cb967_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'out_of_scope'], name='dojo_debt_i_debt_te_4b7f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'false_p'], name='dojo_debt_i_debt_te_1c2f94_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'unique_id_from_tool', 'duplicate'], name='dojo_debt_i_debt_te_286089_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'hash_code', 'duplicate'], name='dojo_debt_i_debt_te_2a7616_idx'),
        ),
        migrations.AddIndex(
            model_name='debt_item',
            index=models.Index(fields=['debt_test', 'component_name'], name='dojo_debt_i_debt_te_7c026d_idx'),
        ),
        migrations.AddField(
            model_name='debt_jira_issue',
            name='debt_engagement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_engagement'),
        ),
        migrations.AddField(
            model_name='debt_jira_issue',
            name='debt_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_item'),
        ),
        migrations.AddField(
            model_name='debt_jira_issue',
            name='debt_item_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_item_group'),
        ),
        migrations.AddField(
            model_name='debt_jira_issue',
            name='jira_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_jira_project'),
        ),
    ]
