# Generated by Django 4.1.11 on 2023-11-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0203_debt_jira_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Risk_Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name which in the future may also be used to group risk acceptances together across debt_engagements and debt_contexts', max_length=300)),
                ('recommendation', models.CharField(choices=[('A', 'Accept (The risk is acknowledged, yet remains)'), ('V', 'Avoid (Do not engage with whatever creates the risk)'), ('M', 'Mitigate (The risk still exists, yet compensating controls make it less of a threat)'), ('F', 'Fix (The risk is eradicated)'), ('T', 'Transfer (The risk is transferred to a 3rd party)')], default='F', help_text='Recommendation from the security team.', max_length=2, verbose_name='Security Recommendation')),
                ('recommendation_details', models.TextField(blank=True, help_text='Explanation of security recommendation', null=True, verbose_name='Security Recommendation Details')),
                ('decision', models.CharField(choices=[('A', 'Accept (The risk is acknowledged, yet remains)'), ('V', 'Avoid (Do not engage with whatever creates the risk)'), ('M', 'Mitigate (The risk still exists, yet compensating controls make it less of a threat)'), ('F', 'Fix (The risk is eradicated)'), ('T', 'Transfer (The risk is transferred to a 3rd party)')], default='A', help_text='Risk treatment decision by risk owner', max_length=2)),
                ('decision_details', models.TextField(blank=True, default=None, help_text='If a compensating control exists to mitigate the debt_item or reduce risk, then list the compensating control(s).', null=True)),
                ('accepted_by', models.CharField(blank=True, default=None, help_text='The person that accepts the risk, can be outside of DefectDojo.', max_length=200, null=True, verbose_name='Accepted By')),
                ('path', models.FileField(blank=True, null=True, upload_to='risk/%Y/%m/%d', verbose_name='Proof')),
                ('expiration_date', models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance expires, the debt_items will be reactivated (unless disabled below).', null=True)),
                ('expiration_date_warned', models.DateTimeField(blank=True, default=None, help_text='(readonly) Date at which notice about the risk acceptance expiration was sent.', null=True)),
                ('expiration_date_handled', models.DateTimeField(blank=True, default=None, help_text='(readonly) When the risk acceptance expiration was handled (manually or by the daily job).', null=True)),
                ('reactivate_expired', models.BooleanField(default=True, help_text='Reactivate debt_items when risk acceptance expires?', verbose_name='Reactivate debt_items on expiration')),
                ('restart_sla_expired', models.BooleanField(default=False, help_text='When enabled, the SLA for debt_items is restarted when the risk acceptance expires.', verbose_name='Restart SLA on expiration')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accepted_debt_items', models.ManyToManyField(to='dojo.debt_item')),
                ('notes', models.ManyToManyField(editable=False, to='dojo.notes')),
                ('owner', models.ForeignKey(help_text='User in DefectDojo owning this acceptance. Only the owner and staff users can edit the risk acceptance.', on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_user')),
            ],
        ),
        migrations.AlterField(
            model_name='debt_engagement',
            name='risk_acceptance',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='dojo.debt_risk_acceptance'),
        ),
    ]
