# Generated by Django 4.1.11 on 2023-11-17 09:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0204_debt_risk_acceptance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Test_Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('import_settings', models.JSONField(null=True)),
                ('type', models.CharField(default='unknown', max_length=64)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('build_id', models.CharField(blank=True, help_text='Build ID that was debt_tested, a reimport may update this field.', max_length=150, null=True, verbose_name='Build ID')),
                ('commit_hash', models.CharField(blank=True, help_text='Commit hash debt_tested, a reimport may update this field.', max_length=150, null=True, verbose_name='Commit Hash')),
                ('branch_tag', models.CharField(blank=True, help_text='Tag or branch that was debt_tested, a reimport may update this field.', max_length=150, null=True, verbose_name='Branch/Tag')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Debt_Test_Import_Debt_Item_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('action', models.CharField(blank=True, choices=[('N', 'created'), ('C', 'closed'), ('R', 'reactivated'), ('U', 'left untouched'), ('N', 'created'), ('C', 'closed'), ('R', 'reactivated'), ('U', 'left untouched')], max_length=100, null=True)),
                ('debt_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_item')),
                ('debt_test_import', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test_import')),
            ],
            options={
                'ordering': ('debt_test_import', 'action', 'debt_item'),
            },
        ),
        migrations.DeleteModel(
            name='Test_Import_Debt_Item_Action',
        ),
        migrations.AddField(
            model_name='debt_test_import',
            name='debt_items_affected',
            field=models.ManyToManyField(through='dojo.Debt_Test_Import_Debt_Item_Action', to='dojo.debt_item'),
        ),
        migrations.AddField(
            model_name='debt_test_import',
            name='debt_test',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test'),
        ),
        migrations.AddIndex(
            model_name='debt_test_import_debt_item_action',
            index=models.Index(fields=['debt_item', 'action', 'debt_test_import'], name='dojo_debt_t_debt_it_d50c3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='debt_test_import_debt_item_action',
            unique_together={('debt_test_import', 'debt_item')},
        ),
        migrations.AddIndex(
            model_name='debt_test_import',
            index=models.Index(fields=['created', 'debt_test', 'type'], name='dojo_debt_t_created_b7a186_idx'),
        ),
    ]
