# Generated by Django 4.1.11 on 2023-11-17 12:49

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dojo', '0206_debt_vulnerability_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Engagement_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('questions', models.ManyToManyField(to='dojo.question')),
            ],
            options={
                'verbose_name': 'Debt Engagement Survey',
                'verbose_name_plural': 'Debt Engagement Surveys',
                'ordering': ('-active', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Debt_General_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_responses', models.IntegerField(default=0)),
                ('generated', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiration', models.DateTimeField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_engagement_survey')),
            ],
            options={
                'verbose_name': 'General Debt Engagement Survey',
                'verbose_name_plural': 'General Debt Engagement Surveys',
            },
        ),
        migrations.CreateModel(
            name='Debt_Answered_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('answered_on', models.DateField(null=True)),
                ('assignee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='debt_assignee', to='dojo.dojo_user')),
                ('debt_engagement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_engagement+', to='dojo.debt_engagement')),
                ('responder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='debt_responder', to='dojo.dojo_user')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_engagement_survey')),
            ],
            options={
                'verbose_name': 'Answered Debt Engagement Survey',
                'verbose_name_plural': 'Answered Debt Engagement Surveys',
            },
        ),
        migrations.CreateModel(
            name='Debt_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('answered_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_answered_survey')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
