# Generated by Django 4.1.11 on 2023-11-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0207_debt_engagement_survey_debt_general_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_item',
            name='found_by',
            field=models.ManyToManyField(editable=False, help_text='The name of the scanner that identified the flaw.', to='dojo.debt_test_type', verbose_name='Found by'),
        ),
    ]
