# Generated by Django 4.1.11 on 2023-11-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0209_debt_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.IntegerField(blank=True, null=True, verbose_name='Number of files')),
                ('blank', models.IntegerField(blank=True, null=True, verbose_name='Number of blank lines')),
                ('comment', models.IntegerField(blank=True, null=True, verbose_name='Number of comment lines')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Number of code lines')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('debt_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_context')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.language_type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_user')),
            ],
            options={
                'unique_together': {('language', 'debt_context')},
            },
        ),
    ]
