# Generated by Django 4.1.11 on 2023-11-20 11:17

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0210_debt_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Debt_App_Analysis_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Debt_App_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('confidence', models.IntegerField(blank=True, null=True, verbose_name='Confidence level')),
                ('version', models.CharField(blank=True, max_length=200, null=True, verbose_name='Version Number')),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=400, null=True)),
                ('website_found', models.URLField(blank=True, max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('debt_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_context')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='dojo.tagulous_debt_app_analysis_tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_user')),
            ],
        ),
    ]
