# Generated by Django 4.1.11 on 2023-11-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0211_tagulous_debt_app_analysis_tags_debt_app_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojometa',
            name='debt_context',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_context_meta', to='dojo.debt_context'),
        ),
        migrations.AddField(
            model_name='dojometa',
            name='debt_item',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_item_meta', to='dojo.debt_item'),
        ),
    ]
