# Generated by Django 4.1.11 on 2023-11-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0212_dojometa_debt_context_dojometa_debt_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojometa',
            name='debt_endpoint',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_endpoint_meta', to='dojo.debt_endpoint'),
        ),
    ]
