# Generated by Django 4.1.11 on 2023-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0213_dojometa_debt_endpoint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debt_test',
            name='dojo_debt_t_debt_en_1d276c_idx',
        ),
        migrations.RenameField(
            model_name='debt_test',
            old_name='test_type',
            new_name='debt_test_type',
        ),
        migrations.AddIndex(
            model_name='debt_test',
            index=models.Index(fields=['debt_engagement', 'debt_test_type'], name='dojo_debt_t_debt_en_49fc9c_idx'),
        ),
    ]
