# Generated by Django 4.1.11 on 2023-11-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0215_remove_debt_context_api_scan_configuration_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Cred_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authn_provider', models.BooleanField(default=False, verbose_name='Authentication Provider')),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('cred_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_cred_user', to='dojo.cred_user', verbose_name='Credential')),
                ('debt_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_context', to='dojo.debt_context')),
                ('debt_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_engagement', to='dojo.debt_engagement')),
                ('debt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_item', to='dojo.debt_item')),
                ('debt_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_test', to='dojo.debt_test')),
            ],
        ),
    ]
