# Generated by Django 4.1.11 on 2023-11-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0217_debt_github_pkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt_item_group',
            name='test',
        ),
        migrations.AddField(
            model_name='debt_item_group',
            name='debt_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test'),
            preserve_default=False,
        ),
    ]
