# Generated by Django 4.1.11 on 2023-11-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0218_remove_debt_item_group_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stub_debt_item',
            name='test',
        ),
        migrations.AddField(
            model_name='stub_debt_item',
            name='debt_test',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.debt_test'),
            preserve_default=False,
        ),
    ]
