# Generated by Django 4.1.11 on 2023-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0220_debt_item_attitude_debt_item_intentionality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_item',
            name='attitude',
            field=models.CharField(help_text='The attitude that led to the creation of this Debt Item (Prudent, Reckless).', max_length=200, verbose_name='Attitude'),
        ),
    ]
