# Generated by Django 4.1.11 on 2023-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0221_alter_debt_item_attitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt_item_template',
            name='attitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt_item_template',
            name='intentionality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
