# Generated by Django 4.1.11 on 2023-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0222_debt_item_template_attitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_acceptance',
            name='accepted_debt_items',
            field=models.ManyToManyField(to='dojo.debt_item'),
        ),
    ]
