# Generated by Django 4.1.11 on 2023-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0223_risk_acceptance_accepted_debt_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_acceptance',
            name='recommendation',
            field=models.CharField(choices=[('A', 'Accept (The risk is acknowledged, yet remains)'), ('V', 'Avoid (Do not engage with whatever creates the risk)'), ('M', 'Mitigate (The risk still exists, yet compensating controls make it less of a threat)'), ('F', 'Fix (The risk is eradicated)'), ('T', 'Transfer (The risk is transferred to a 3rd party)')], default='F', help_text='Recommendation from the security team.', max_length=2, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='risk_acceptance',
            name='recommendation_details',
            field=models.TextField(blank=True, help_text='Explanation of security recommendation', null=True, verbose_name='Recommendation Details'),
        ),
    ]
