# Generated by Django 4.1.11 on 2023-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0224_alter_risk_acceptance_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt_item',
            name='payment_cost',
            field=models.CharField(default=1, help_text='The level of cost for paying this Debt Item in t-shirt sizing (XL, L, M, S, XS).', max_length=200, verbose_name='Payment Cost'),
            preserve_default=False,
        ),
    ]
