# Generated by Django 4.1.11 on 2023-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0225_debt_item_payment_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_risk_acceptance',
            name='decision',
            field=models.CharField(choices=[('A', 'Accept (The debt is acknowledged, yet remains)'), ('M', 'Mitigate (The debt still exists, yet compensating actions make it less of a problem)'), ('P', 'Pay (The debt is eliminated)'), ('T', 'Transfer (The debt is transferred to a 3rd party)')], default='A', help_text='Risk treatment decision by risk owner', max_length=2),
        ),
        migrations.AlterField(
            model_name='debt_risk_acceptance',
            name='recommendation',
            field=models.CharField(choices=[('A', 'Accept (The debt is acknowledged, yet remains)'), ('M', 'Mitigate (The debt still exists, yet compensating actions make it less of a problem)'), ('P', 'Pay (The debt is eliminated)'), ('T', 'Transfer (The debt is transferred to a 3rd party)')], default='P', help_text='Recommendation from the security team.', max_length=2, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='debt_risk_acceptance',
            name='recommendation_details',
            field=models.TextField(blank=True, help_text='Explanation of security recommendation', null=True, verbose_name='Recommendation Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='business_criticality',
            field=models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low'), ('None', 'None')], max_length=9, null=True),
        ),
    ]
