# Generated by Django 4.1.11 on 2023-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0226_alter_debt_risk_acceptance_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_risk_acceptance',
            name='recommendation_details',
            field=models.TextField(blank=True, help_text='Explanation of recommendation', null=True, verbose_name='Recommendation Details'),
        ),
    ]
