# Generated by Django 4.1.11 on 2023-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0229_alter_debt_risk_acceptance_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_item',
            name='mitigation',
            field=models.TextField(blank=True, help_text='Text describing how to best fix the flaw.', null=True, verbose_name='Payment / Mitigation action'),
        ),
    ]
