# Generated by Django 4.1.11 on 2023-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0230_alter_debt_item_mitigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_risk_acceptance',
            name='reactivate_expired',
            field=models.BooleanField(default=True, help_text='Reactivate Debt Items when risk acceptance expires?', verbose_name='Reactivate Debt Items on expiration'),
        ),
    ]
