# Generated by Django 4.1.11 on 2023-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0231_alter_debt_risk_acceptance_reactivate_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt_item',
            name='artifact',
            field=models.CharField(default=1, help_text='The artifact suffering from the debt.', max_length=200, verbose_name='Artifact'),
            preserve_default=False,
        ),
    ]
