# Generated by Django 4.1.11 on 2024-02-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0235_debt_notifications_scan_added_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt_item',
            name='nb_of_votes',
            field=models.IntegerField(blank=True, default=0, help_text='The number of votes cast for this debt item.', null=True, verbose_name='Number of votes'),
        ),
    ]
