# Generated by Django 4.1.11 on 2024-03-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0236_debt_item_nb_of_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt_risk_acceptance',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='debt_risk_acceptance',
            name='recommendation_details',
        ),
    ]
