from django.urls import re_path

from dojo.debt_engagement import views

urlpatterns = [
    #  debt_engagements and calendar
    re_path(r'^calendar$', views.debt_engagement_calendar, name='calendar'),
    re_path(r'^calendar/debt_engagements$', views.debt_engagement_calendar, name='debt_engagement_calendar'),
    re_path(r'^debt_engagement$', views.debt_engagements, {'view': 'active'}, name='debt_engagement'),
    re_path(r'^debt_engagements_all$', views.debt_engagements_all, name='debt_engagements_all'),
    re_path(r'^debt_engagement/all$', views.debt_engagements, {'view': 'all'}, name='all_debt_engagements'),
    re_path(r'^debt_engagement/active$', views.debt_engagements, {'view': 'active'}, name='active_debt_engagements'),
    re_path(r'^debt_engagement/(?P<eid>\d+)$', views.view_debt_engagement,
        name='view_debt_engagement'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/ics$', views.debt_engagement_ics,
        name='debt_engagement_ics'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/edit$', views.edit_debt_engagement,
        name='edit_debt_engagement'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/delete$', views.delete_debt_engagement,
        name='delete_debt_engagement'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/copy$', views.copy_debt_engagement,
        name='copy_debt_engagement'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/add_debt_tests$', views.add_debt_tests,
        name='add_debt_tests'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/import_scan_results$',
        views.import_scan_results, name='import_scan_results'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/close$', views.close_eng,
        name='close_debt_engagement'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/reopen$', views.reopen_eng,
        name='reopen_debt_engagement'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/complete_checklist$',
        views.complete_checklist, name='complete_checklist'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/add$',
        views.add_risk_acceptance, name='add_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/add/(?P<fid>\d+)$',
        views.add_risk_acceptance, name='add_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/(?P<raid>\d+)$',
        views.view_risk_acceptance, name='view_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/(?P<raid>\d+)/edit$',
        views.edit_risk_acceptance, name='edit_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/(?P<raid>\d+)/expire$',
        views.expire_risk_acceptance, name='expire_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/(?P<raid>\d+)/reinstate$',
        views.reinstate_risk_acceptance, name='reinstate_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/(?P<raid>\d+)/delete$',
        views.delete_risk_acceptance, name='delete_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/risk_acceptance/(?P<raid>\d+)/download$',
        views.download_risk_acceptance, name='download_risk_acceptance'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/threatmodel$', views.view_threatmodel,
        name='view_threatmodel'),
    re_path(r'^debt_engagement/(?P<eid>\d+)/threatmodel/upload$',
        views.upload_threatmodel, name='upload_threatmodel'),
    re_path(r'^debt_engagement/csv_export$',
        views.csv_export, name='debt_engagement_csv_export'),
    re_path(r'^debt_engagement/excel_export$',
        views.excel_export, name='debt_engagement_excel_export'),
]
