from django.urls import re_path

from dojo.debt_context import views

urlpatterns = [
    #  debt_context
    re_path(r'^debt_context$', views.debt_context, name='debt_context'),
    re_path(r'^debt_context/(?P<pid>\d+)$', views.view_debt_context,
        name='view_debt_context'),
    re_path(r'^debt_context/(?P<pid>\d+)/components$', views.view_debt_context_components,
        name='view_debt_context_components'),
    re_path(r'^debt_context/(?P<pid>\d+)/debt_engagements$', views.view_debt_engagements,
        name='view_debt_engagements'),
    re_path(r'^debt_context/(?P<pid>\d+)/import_scan_results$',
        views.import_scan_results_debt_context, name='import_scan_results_debt_context'),
    re_path(r'^debt_context/(?P<pid>\d+)/metrics$', views.view_debt_context_metrics,
        name='view_debt_context_metrics'),
    re_path(r'^debt_context/(?P<pid>\d+)/async_burndown_metrics$', views.async_burndown_metrics,
        name='async_burndown_metrics'),
    re_path(r'^debt_context/(?P<pid>\d+)/edit$', views.edit_debt_context,
        name='edit_debt_context'),
    re_path(r'^debt_context/(?P<pid>\d+)/delete$', views.delete_debt_context,
        name='delete_debt_context'),
    re_path(r'^debt_context/add', views.new_debt_context, name='new_debt_context'),
    re_path(r'^debt_context/(?P<pid>\d+)/new_debt_engagement$', views.new_eng_for_app,
        name='new_eng_for_debt_context'),
    re_path(r'^debt_context/(?P<pid>\d+)/new_technology$', views.new_tech_for_debt_context,
         name='new_tech_for_debt_context'),
    re_path(r'^technology/(?P<tid>\d+)/edit$', views.edit_technology,
        name='edit_technology'),
    re_path(r'^technology/(?P<tid>\d+)/delete$', views.delete_technology,
        name='delete_technology'),
    re_path(r'^debt_context/(?P<pid>\d+)/new_debt_engagement/cicd$', views.new_eng_for_app_cicd,
        name='new_eng_for_debt_context_cicd'),
    re_path(r'^debt_context/(?P<pid>\d+)/add_meta_data$', views.add_meta_data,
        name='add_meta_data'),
    re_path(r'^debt_context/(?P<pid>\d+)/edit_notifications$', views.edit_notifications,
        name='edit_notifications'),
    re_path(r'^debt_context/(?P<pid>\d+)/edit_meta_data$', views.edit_meta_data,
        name='edit_meta_data'),
    re_path(
        r'^debt_context/(?P<debt_context_id>\d+)/ad_hoc_debt_item$',
        views.AdHocDebtItemView.as_view(),
        name='ad_hoc_debt_item'),
    re_path(r'^debt_context/(?P<pid>\d+)/debt_engagement_presets$', views.debt_engagement_presets,
        name='debt_engagement_presets'),
    re_path(r'^debt_context/(?P<pid>\d+)/debt_engagement_presets/(?P<eid>\d+)/edit$', views.edit_debt_engagement_presets,
        name='edit_debt_engagement_presets'),
    re_path(r'^debt_context/(?P<pid>\d+)/debt_engagement_presets/add$', views.add_debt_engagement_presets,
        name='add_debt_engagement_presets'),
    re_path(r'^debt_context/(?P<pid>\d+)/debt_engagement_presets/(?P<eid>\d+)/delete$', views.delete_debt_engagement_presets,
        name='delete_debt_engagement_presets'),
    re_path(r'^debt_context/(?P<pid>\d+)/add_member$', views.add_debt_context_member,
        name='add_debt_context_member'),
    re_path(r'^debt_context/member/(?P<memberid>\d+)/edit$', views.edit_debt_context_member,
        name='edit_debt_context_member'),
    re_path(r'^debt_context/member/(?P<memberid>\d+)/delete$', views.delete_debt_context_member,
        name='delete_debt_context_member'),
    re_path(r'^debt_context/(?P<pid>\d+)/add_api_scan_configuration$', views.add_api_scan_configuration,
        name='add_api_scan_configuration'),
    re_path(r'^debt_context/(?P<pid>\d+)/view_api_scan_configurations$', views.view_api_scan_configurations,
        name='view_api_scan_configurations'),
    re_path(r'^debt_context/(?P<pid>\d+)/edit_api_scan_configuration/(?P<pascid>\d+)$', views.edit_api_scan_configuration,
        name='edit_api_scan_configuration'),
    re_path(r'^debt_context/(?P<pid>\d+)/delete_api_scan_configuration/(?P<pascid>\d+)$', views.delete_api_scan_configuration,
        name='delete_api_scan_configuration'),
    re_path(r'^debt_context/(?P<pid>\d+)/add_group$', views.add_debt_context_group,
        name='add_debt_context_group'),
    re_path(r'^debt_context/group/(?P<groupid>\d+)/edit$', views.edit_debt_context_group,
        name='edit_debt_context_group'),
    re_path(r'^debt_context/group/(?P<groupid>\d+)/delete$', views.delete_debt_context_group,
        name='delete_debt_context_group'),
]
